#!/usr/bin/env node

"use strict";

var Hoerdat = require('./index');

let attributes = {};
process.argv.slice(2).forEach(function(param) {
  let params = param.split("=");
  attributes[params[0]] = params[1];
});

Hoerdat.query(attributes).then(function(res) {
  console.log(JSON.stringify(res, null, 2));
}).catch(function(err) {
  console.error(err);
});
