#!/usr/bin/env node

"use strict";

var Hoerdat = require('./index');

Hoerdat.query({
  title: 'Jim Knopf',
  authorFirstname: 'Michael',
  authorName: 'Ende'
}).then(function(res) {
  console.log(JSON.stringify(res, null, 2));
}).catch(function(err) {
  console.error(err);
});
